import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  compiledValorantAssetPath,
  type ValorantAssetKind,
} from './valorant-asset-config.ts';
import {
  publishValorantMetadataTransaction,
  type MetadataHashes,
} from './valorant-metadata-transaction.ts';

interface ValorantApiRecord {
  uuid?: unknown;
  displayName?: unknown;
  developerName?: unknown;
  displayIcon?: unknown;
  mapUrl?: unknown;
  splash?: unknown;
  assetPath?: unknown;
}

interface ValorantApiResponse {
  status: number;
  data: ValorantApiRecord[];
}

const AGENTS_EN_URL = 'https://valorant-api.com/v1/agents?language=en-US&isPlayableCharacter=true';
const AGENTS_ZH_URL = 'https://valorant-api.com/v1/agents?language=zh-CN&isPlayableCharacter=true';
const MAPS_ZH_URL = 'https://valorant-api.com/v1/maps?language=zh-CN';
const MODES_EN_URL = 'https://valorant-api.com/v1/gamemodes?language=en-US';
const MODES_ZH_URL = 'https://valorant-api.com/v1/gamemodes?language=zh-CN';
const MEDIA_ORIGIN = 'https://media.valorant-api.com';
const MAX_ASSET_BYTES = 16 * 1024 * 1024;
const DOWNLOAD_CONCURRENCY = 6;

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_ROOT = join(REPO_ROOT, 'packages', 'gui', 'assets', 'valorant-source');
const OUT_FILE = join(
  REPO_ROOT,
  'packages',
  'gui',
  'src',
  'utils',
  'generated',
  'valorant-metadata.zh-CN.ts',
);

const [agentsEn, agentsZh, mapsZh, modesEn, modesZh] = await Promise.all([
  fetchData(AGENTS_EN_URL),
  fetchData(AGENTS_ZH_URL),
  fetchData(MAPS_ZH_URL),
  fetchData(MODES_EN_URL),
  fetchData(MODES_ZH_URL),
]);

const agentsZhById = recordsByUuid(agentsZh, 'zh-CN agent');
const modesZhById = recordsByUuid(modesZh, 'zh-CN game mode');

const agentDownloads = agentsEn.map((record) => {
  const uuid = requiredString(record.uuid, 'agent uuid');
  const localized = agentsZhById.get(uuid);
  if (!localized) throw new Error(`zh-CN agent missing for ${uuid}`);
  return {
    uuid,
    en: requiredString(record.displayName, `agent ${uuid} displayName`),
    developerName: requiredString(record.developerName, `agent ${uuid} developerName`),
    cn: requiredString(localized.displayName, `agent ${uuid} zh-CN displayName`),
    sourceImage: canonicalMediaUrl(localized.displayIcon, `agent ${uuid} displayIcon`),
  };
}).sort((a, b) => a.en.localeCompare(b.en, 'en'));

const mapDownloads = mapsZh.map((record) => {
  const uuid = requiredString(record.uuid, 'map uuid');
  return {
    uuid,
    mapUrl: requiredString(record.mapUrl, `map ${uuid} mapUrl`).replace(/\\/g, '/'),
    cn: requiredString(record.displayName, `map ${uuid} zh-CN displayName`),
    sourceImage: canonicalMediaUrl(record.splash, `map ${uuid} splash`),
  };
}).sort((a, b) => a.mapUrl.localeCompare(b.mapUrl, 'en'));

const modeDownloads = modesEn.flatMap((record) => {
  const uuid = requiredString(record.uuid, 'game mode uuid');
  const localized = modesZhById.get(uuid);
  if (!localized) throw new Error(`zh-CN game mode missing for ${uuid}`);
  const sourceImage = optionalCanonicalMediaUrl(localized.displayIcon, `game mode ${uuid} displayIcon`);
  if (!sourceImage) return [];
  return [{
    uuid,
    en: requiredString(record.displayName, `game mode ${uuid} displayName`),
    cn: requiredString(localized.displayName, `game mode ${uuid} zh-CN displayName`),
    assetPath: requiredString(record.assetPath, `game mode ${uuid} assetPath`).replace(/\\/g, '/'),
    sourceImage,
  }];
}).sort((a, b) => a.en.localeCompare(b.en, 'en'));

assertUnique(agentDownloads, 'uuid', 'agent UUID');
assertUnique(agentDownloads, 'en', 'agent English name');
assertUnique(mapDownloads, 'uuid', 'map UUID');
assertUnique(mapDownloads, 'mapUrl', 'map URL');
assertUnique(modeDownloads, 'uuid', 'game mode UUID');
assertUnique(modeDownloads, 'assetPath', 'game mode asset path');

await publishValorantMetadataTransaction({
  sourceRoot: SOURCE_ROOT,
  metadataFile: OUT_FILE,
  concurrency: DOWNLOAD_CONCURRENCY,
  groups: [
    { kind: 'agents', records: agentDownloads },
    { kind: 'maps', records: mapDownloads },
    { kind: 'gamemodes', records: modeDownloads },
  ],
  download: downloadPng,
  renderMetadata(hashes) {
    const agents = agentDownloads.map(({ sourceImage: _sourceImage, ...record }) =>
      withCompiledAsset(record, 'agents', requiredHashForKind(hashes, 'agents', record.uuid)));
    const maps = mapDownloads.map(({ sourceImage: _sourceImage, ...record }) =>
      withCompiledAsset(record, 'maps', requiredHashForKind(hashes, 'maps', record.uuid)));
    const gameModes = modeDownloads.map(({ sourceImage: _sourceImage, ...record }) =>
      withCompiledAsset(record, 'gamemodes', requiredHashForKind(hashes, 'gamemodes', record.uuid)));

    return `// Generated by tools/update-valorant-metadata.ts. Do not hand-edit.
// Metadata sources:
// - ${AGENTS_EN_URL}
// - ${AGENTS_ZH_URL}
// - ${MAPS_ZH_URL}
// - ${MODES_EN_URL}
// - ${MODES_ZH_URL}
// Source media origin: ${MEDIA_ORIGIN}
// Source PNGs: content-addressed under packages/gui/assets/valorant-source
// Runtime WebP: generated by tools/build-valorant-assets.ts under packages/gui/public/valorant
// Records: ${agents.length} agents, ${maps.length} maps, ${gameModes.length} game modes with icons

export interface ValorantAgentMetadata {
  uuid: string;
  en: string;
  developerName: string;
  cn: string;
  image: string;
  sourceSha256: string;
}

export interface ValorantMapMetadata {
  uuid: string;
  mapUrl: string;
  cn: string;
  image: string;
  sourceSha256: string;
}

export interface ValorantGameModeMetadata {
  uuid: string;
  en: string;
  cn: string;
  assetPath: string;
  image: string;
  sourceSha256: string;
}

export const VALORANT_AGENTS: readonly ValorantAgentMetadata[] = ${JSON.stringify(agents, null, 2)};

export const VALORANT_MAPS: readonly ValorantMapMetadata[] = ${JSON.stringify(maps, null, 2)};

export const VALORANT_GAME_MODES: readonly ValorantGameModeMetadata[] = ${JSON.stringify(gameModes, null, 2)};
`;
  },
});
console.log(
  `Wrote ${agentDownloads.length} agents, ${mapDownloads.length} maps, and ${modeDownloads.length} game modes to ${OUT_FILE}`,
);

async function fetchData(url: string): Promise<ValorantApiRecord[]> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`GET ${url} failed: ${response.status} ${response.statusText}`);
  }
  const payload = await response.json() as ValorantApiResponse;
  if (!Array.isArray(payload.data)) {
    throw new Error(`GET ${url} payload missing data[]`);
  }
  return payload.data;
}

function recordsByUuid(records: ValorantApiRecord[], label: string): Map<string, ValorantApiRecord> {
  const out = new Map<string, ValorantApiRecord>();
  for (const record of records) {
    const uuid = requiredString(record.uuid, `${label} uuid`);
    if (out.has(uuid)) throw new Error(`duplicate ${label} UUID: ${uuid}`);
    out.set(uuid, record);
  }
  return out;
}

function requiredString(value: unknown, field: string): string {
  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(`${field} must be a non-empty string`);
  }
  return value.trim();
}

function optionalCanonicalMediaUrl(value: unknown, field: string): string | undefined {
  if (value == null || value === '') return undefined;
  return canonicalMediaUrl(value, field);
}

function canonicalMediaUrl(value: unknown, field: string): string {
  const url = new URL(requiredString(value, field));
  if (url.origin !== MEDIA_ORIGIN || url.protocol !== 'https:') {
    throw new Error(`${field} must use ${MEDIA_ORIGIN}`);
  }
  return url.href;
}

async function downloadPng(url: string): Promise<{ bytes: Uint8Array; hash: string }> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`GET ${url} failed: ${response.status} ${response.statusText}`);
  }
  const declaredBytes = Number(response.headers.get('content-length') ?? 0);
  if (Number.isFinite(declaredBytes) && declaredBytes > MAX_ASSET_BYTES) {
    throw new Error(`${url} exceeds the ${MAX_ASSET_BYTES} byte limit`);
  }
  const bytes = new Uint8Array(await response.arrayBuffer());
  if (bytes.byteLength === 0 || bytes.byteLength > MAX_ASSET_BYTES) {
    throw new Error(`${url} has invalid size ${bytes.byteLength}`);
  }
  if (!isPng(bytes)) throw new Error(`${url} is not a PNG file`);
  const hash = createHash('sha256').update(bytes).digest('hex');
  return { bytes, hash };
}

function isPng(bytes: Uint8Array): boolean {
  const signature = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
  return signature.every((value, index) => bytes[index] === value);
}

function requiredHashForKind(
  hashes: MetadataHashes,
  kind: ValorantAssetKind,
  uuid: string,
): string {
  const hash = hashes.get(kind)?.get(uuid);
  if (!hash) throw new Error(`missing downloaded asset hash for ${uuid}`);
  return hash;
}

function withCompiledAsset<T extends Record<string, unknown>>(
  record: T,
  kind: ValorantAssetKind,
  sourceSha256: string,
): T & { image: string; sourceSha256: string } {
  return {
    ...record,
    image: compiledValorantAssetPath(kind, sourceSha256),
    sourceSha256,
  };
}

function assertUnique<T extends Record<string, unknown>>(
  records: T[],
  key: keyof T,
  label: string,
): void {
  const seen = new Set<unknown>();
  for (const record of records) {
    if (seen.has(record[key])) throw new Error(`duplicate ${label}: ${String(record[key])}`);
    seen.add(record[key]);
  }
}
