import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

interface ValorantSkin {
  displayName?: unknown;
  assetPath?: unknown;
}

interface ValorantSkinResponse {
  status: number;
  data: ValorantSkin[];
}

const SOURCE_URL = 'https://valorant-api.com/v1/weapons/skins?language=zh-CN';
const OUT_FILE = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'packages',
  'gui',
  'src',
  'utils',
  'generated',
  'valorant-skins.zh-CN.ts',
);

const response = await fetch(SOURCE_URL);
if (!response.ok) {
  throw new Error(`GET ${SOURCE_URL} failed: ${response.status} ${response.statusText}`);
}

const payload = await response.json() as ValorantSkinResponse;
if (!Array.isArray(payload.data)) {
  throw new Error('Valorant API payload missing data[]');
}

const skinNames: Record<string, string> = {};
for (const skin of payload.data) {
  if (typeof skin.displayName !== 'string' || typeof skin.assetPath !== 'string') continue;
  const key = skinAssetKey(skin.assetPath);
  if (!key) continue;
  skinNames[key] = skin.displayName;
}

const sorted = Object.fromEntries(
  Object.entries(skinNames).sort(([a], [b]) => a.localeCompare(b)),
);
const generatedAt = new Date().toISOString();
const body = `// Generated by tools/update-valorant-skins.ts
// Source: ${SOURCE_URL}
// Language: zh-CN
// Generated at: ${generatedAt}
// Records: ${Object.keys(sorted).length}

export const VALORANT_SKIN_CN: Record<string, string> = ${JSON.stringify(sorted, null, 2)};
`;

await Bun.write(OUT_FILE, body);
console.log(`Wrote ${Object.keys(sorted).length} skins to ${OUT_FILE}`);

function skinAssetKey(assetPath: string): string {
  const last = assetPath.split('/').pop() ?? '';
  return last.replace(/_PrimaryAsset$/, '').trim();
}
