name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install
      - run: bun run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wonderful-ui-${{ github.ref_name }}
          path: src-tauri/target/release/bundle/
